name: Hexo Deploy

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          echo "Installing npm dependencies..."
          npm install

      - name: Show project structure before Hexo build
        run: |
          echo "Listing current directory:"
          ls -al
          echo "Checking Hexo version:"
          npx hexo version

      - name: Generate static files
        run: |
          echo "Running Hexo generate..."
          npx hexo generate
        continue-on-error: true

      - name: Show output directory after build
        run: |
          echo "Listing ./public contents:"
          ls -al ./public || echo "Public directory not found."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
